### ISSUE TITLE
Comments uncompatible with documentation

### ISSUE THREAD

**Issue by malpunek** [fbsamples/messenger-bot-samples#32]
Official [docs](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/#format) clearly say: 
![msg_issue](https://user-images.githubusercontent.com/13259207/42642188-93dfce66-85f6-11e8-8653-8594ca6ef566.png)

However `messenger-bot-samples/account-linking/routes/webhooks.js:65-66` have the following two lines:
```
// Iterate over each messaging event
pageEntry.messaging.forEach((messagingEvent) => {
```
I find the lines very misleading.

**Comment by embee8** [comment]
The screenshot above says that the webhook event contains a `messaging` field (first column) that is an array (second column) with one element (third column). Therefore, the code treats this field as an array and iterates over it. Because there is only one `messagingEvent`, it will only be passed through once.

I hope this clarifies it for you. If not, please elaborate on how you find this misleading.
